# -*- coding: utf-8 -*-
"""GraphBmi.ipynb

Automatically generated by Colaboratory.

GraphBmi by Inthat Soonthornsap under MIT License.
"""

#from google.colab import drive
#drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
#Remove the comment if you want to get Colaboratory edition or get the file in my github repository:https://github.com/mopokan/IPST-Code.git
# %cd /content
#!git clone https://github.com/mopokan/IPST-Code.git

import pandas as pd
import matplotlib.pyplot as plt

data=pd.read_csv(('/Destination path/BMI.csv') ,names=['ID', 'Gender', 'CsScore', 'Height', 'BMI'])
df=pd.DataFrame(data)
newData=data
print(df)
x=df['ID']
data=df['BMI']
newData.ID.hist(range=[5884,5921],bins=21)
plt.title('BMI Table')
plt.axis([5884,5921,0,32])
plt.xlabel('ID')
plt.ylabel('BMI')
plt.xticks(range(5884,5921,2))

plt.bar(x,data)
