# -*- coding: utf-8 -*-
"""read_csv

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cD3PRXagai91Zf8mDAG2Iz5lgWFMe3xh
"""

!wget https://raw.githubusercontent.com/mopokan/IPST-Code/master/BMI.csv --no-check-certificate

import pandas as pd
stdData=pd.read_csv('BMI.csv',delimiter=',',names=['ID','Gender','Csscore','Height'])#your location path like C:/User/Bmi.csv
print(stdData)